apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"

namePrefix: prod-

configMapGenerator:
  - envs:
      - ".env"
    name: helloworld

patches:
  - path: deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: helloworld
    
  - path: service-patch.yaml
    target:
      version: v1
      kind: Service
      name: helloworld
    
  - path: ingress-patch.yaml
    target:
      group: networking.istio.io
      version: v1alpha3
      kind: VirtualService
      name: helloworld
